services:
  backend:
    container_name: meditate 
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATA_PATH: ${DATA_PATH}
      DATA_FILE_NAME: ${DATA_FILE_NAME}
    volumes:
      - ${HOST_DATA_PATH}:${DATA_PATH}
    ports:
      - 8080:8080 
