services:
  meditation:
    container_name: meditation
    image: ${IMAGE}
    environment:
      DATA_PATH: ${DATA_PATH}
      DATA_FILE_NAME: ${DATA_FILE_NAME}
    volumes:
      - ${HOST_DATA_PATH}:${DATA_PATH}
    ports:
      - 8080:8080 
    restart: always